// GENERATED by scripts/fonts/build.mjs — do not hand-edit. Intentionally import-free.

export interface FontFile {
  path: string;
  r2Key: string;
  bytes: number;
  sha256: string;
}

export interface FontVariant {
  weight: number;
  style: "normal" | "italic";
  files: { latin: FontFile; latinExt?: FontFile };
}

export interface FontFamily {
  key: string;
  name: string;
  group: string;
  cssFallback: string;
  license: string;
  source: { provider: string; id: string; npmVersion: string };
  aliases: string[];
  preview: string;
  variants: FontVariant[];
}

export interface FontManifest {
  version: number;
  generatedAt: string;
  groups: Record<string, string>;
  fallbackKey: string;
  families: FontFamily[];
}
