// T2.13 parity fixture — BROWSER engine side (merge-blocking drift alarm).
// Renders the shared fixture through `satori/standalone` initialized with satori's own packaged
// yoga.wasm — the EXACT engine pair useSatoriRenderer ships to the editor — and asserts the SVG
// is byte-identical to the committed golden (which was generated by the EDGE engine,
// npm:satori; supabase/functions/__tests__/estudio-render-parity_test.ts re-asserts that side).
// If this fails after a satori/yoga/font/tree change: the two engines no longer draw the same
// pixels, and the editor preview is lying about what design-render will produce. Fix the drift
// (or, for an INTENTIONAL rendering change, regenerate the golden and prove both suites pass).
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import satori, { init } from 'satori/standalone';
import { buildPageTree } from '@mesaas/design-render-tree';
import {
  PARITY_CANVAS,
  PARITY_DOC,
  PARITY_FONT_FILES,
} from '../supabase/functions/_shared/parity-fixture';

const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(here, '..');

describe('estudio render parity (browser engine: satori/standalone + yoga.wasm)', () => {
  it('produces the byte-identical golden SVG', async () => {
    await init(await readFile(path.join(repoRoot, 'node_modules/satori/yoga.wasm')));

    const fonts = [];
    for (const f of PARITY_FONT_FILES) {
      fonts.push({
        name: f.family,
        data: await readFile(path.join(repoRoot, 'public/fonts/estudio', f.path)),
        weight: f.weight,
        style: f.style,
      });
    }

    const tree = buildPageTree(PARITY_DOC, 0, () => {
      throw new Error('parity fixture has no image layers');
    });

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const svg = await satori(tree as any, {
      width: PARITY_CANVAS.width,
      height: PARITY_CANVAS.height,
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      fonts: fonts as any,
    });

    const golden = await readFile(path.join(repoRoot, 'test/parity/estudio-parity-golden.svg'), 'utf8');
    // Length first: a mismatch message with two 70KB strings is useless — the sizes localize it.
    expect(svg.length).toBe(golden.length);
    expect(svg).toBe(golden);
  }, 30_000);
});
