// scripts/build-report-fonts.ts
// One-off generator: fetches latin WOFF2 subsets from Google Fonts and emits
// supabase/functions/_shared/report-template/fonts.ts with base64 @font-face rules.
// Run manually when fonts change: deno run --allow-net --allow-write scripts/build-report-fonts.ts

const FAMILIES = [
  { css: 'Fraunces:opsz,wght@9..144,500;9..144,600', name: 'Fraunces', weights: [500, 600] },
  {
    css: 'Instrument+Sans:wght@400;500;600;700',
    name: 'Instrument Sans',
    weights: [400, 500, 600, 700],
  },
];
// Chrome UA → Google returns woff2 with unicode-range subsets
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';

let css = '';
for (const fam of FAMILIES) {
  const res = await fetch(`https://fonts.googleapis.com/css2?family=${fam.css}&display=swap`, {
    headers: { 'User-Agent': UA },
  });
  css += (await res.text()) + '\n';
}

// Split into individual @font-face blocks (Google's CSS response is a flat
// sequence of `@font-face { ... }` rules, each usually preceded by a comment
// naming the subset, e.g. `/* latin */`). We keep only the blocks whose
// preceding comment is exactly the latin subset marker — other locales
// (latin-ext, cyrillic, vietnamese, etc.) are dropped to keep file size sane.
const faceBlocks = css.match(/(?:\/\*\s*[\w-]+\s*\*\/\s*)?@font-face\s*\{[^}]*\}/g) ?? [];
const latinBlocks = faceBlocks.filter((block) => /\/\*\s*latin\s*\*\//.test(block));

if (latinBlocks.length === 0) {
  console.error(
    'No latin @font-face blocks found — Google Fonts CSS response format may have changed. ' +
      'Inspect the raw `css` variable and adjust the parsing regex above.',
  );
  Deno.exit(1);
}

let out = '';
for (const block of latinBlocks) {
  const m = block.match(/url\((https:[^)]+\.woff2)\)/);
  if (!m) continue;
  const bin = new Uint8Array(await (await fetch(m[1])).arrayBuffer());
  let b64 = '';
  const CHUNK = 0x8000;
  for (let i = 0; i < bin.length; i += CHUNK) {
    b64 += String.fromCharCode(...bin.subarray(i, i + CHUNK));
  }
  b64 = btoa(b64);
  out +=
    block
      .replace(/\/\*\s*latin\s*\*\/\s*/, '')
      .replace(m[1], `data:font/woff2;base64,${b64}`)
      .trim() + '\n';
}

const file = `// GENERATED by scripts/build-report-fonts.ts — do not edit by hand.
// Fraunces 500/600 + Instrument Sans 400/500/600/700, latin subset, base64 woff2.
export const REPORT_FONTS_CSS = ${JSON.stringify(out)};
`;
await Deno.writeTextFile('supabase/functions/_shared/report-template/fonts.ts', file);
console.log(`fonts.ts written: ${(file.length / 1024).toFixed(0)}KB`);
