-- =============================================================
-- Normalize the adopted client tables to production's exact shape
--
-- Migration 20260727000001 declared `id bigint GENERATED BY DEFAULT AS IDENTITY`
-- while production has a plain `bigint NOT NULL` with a sequence default
-- (`nextval('cliente_enderecos_id_seq')`). Because CREATE TABLE IF NOT EXISTS
-- no-ops in production, the difference only materialises in environments built
-- from migrations — staging now has identity columns where production has
-- sequence defaults.
--
-- That migration's post-condition checked column-NAME presence only, so it
-- reported success across the divergence: the same class of silent drift the
-- reconciliation exists to remove, reproduced one level down.
--
-- This migration converges both environments on production's form (which is
-- also the convention elsewhere in this schema — `clientes` is bigserial), then
-- asserts the full shape: types, nullability, defaults and the CHECK constraint.
--
-- No-op in production. On identity-based environments it swaps the identity for
-- an equivalent owned sequence, preserving the current high-water mark so no id
-- is ever reissued.
-- =============================================================

DO $$
DECLARE
  t       text;
  seq     text;
  next_id bigint;
BEGIN
  FOREACH t IN ARRAY ARRAY['cliente_enderecos', 'cliente_datas'] LOOP
    IF NOT EXISTS (SELECT 1 FROM information_schema.tables
                   WHERE table_schema='public' AND table_name=t) THEN
      RAISE NOTICE 'skip % — table absent', t;
      CONTINUE;
    END IF;

    IF NOT EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_schema='public' AND table_name=t
        AND column_name='id' AND is_identity='YES'
    ) THEN
      RAISE NOTICE 'skip %.id — already sequence-backed (matches production)', t;
      CONTINUE;
    END IF;

    seq := format('public.%I', t || '_id_seq');

    -- Lock BEFORE reading the high-water mark. Reading max(id) first would leave
    -- a window in which the identity's still-live sequence hands `next_id` to a
    -- concurrent INSERT that then commits; setval(..., next_id, false) below
    -- would prime the new sequence to reissue that same value, and the next
    -- ordinary app insert would die on a duplicate primary key.
    --
    -- DROP IDENTITY takes ACCESS EXCLUSIVE anyway, so taking it explicitly one
    -- statement earlier costs nothing and closes the window: once held, no other
    -- transaction can insert between the read and the sequence takeover.
    EXECUTE format('LOCK TABLE public.%I IN ACCESS EXCLUSIVE MODE', t);

    EXECUTE format('SELECT COALESCE(max(id), 0) + 1 FROM public.%I', t) INTO next_id;

    EXECUTE format('ALTER TABLE public.%I ALTER COLUMN id DROP IDENTITY IF EXISTS', t);
    EXECUTE format('CREATE SEQUENCE IF NOT EXISTS %s', seq);
    EXECUTE format('SELECT setval(%L, %s, false)', seq, next_id);
    EXECUTE format('ALTER SEQUENCE %s OWNED BY public.%I.id', seq, t);
    EXECUTE format('ALTER TABLE public.%I ALTER COLUMN id SET DEFAULT nextval(%L::regclass)',
                   t, seq);

    RAISE NOTICE 'normalized %.id — identity replaced by % starting at %', t, seq, next_id;
  END LOOP;
END $$;

-- -------------------------------------------------------------
-- Real shape assertion: type, nullability and identity-ness per column, plus
-- the CHECK constraint. Column-name presence alone is what let the original
-- divergence through.
-- -------------------------------------------------------------
DO $$
DECLARE
  problem text;
BEGIN
  SELECT string_agg(
           e.tbl || '.' || e.col || ' (' ||
           CASE WHEN c.column_name IS NULL THEN 'missing'
                WHEN c.data_type IS DISTINCT FROM e.typ
                  THEN 'type ' || c.data_type || ' <> ' || e.typ
                WHEN c.is_nullable IS DISTINCT FROM e.nullable
                  THEN 'nullable ' || c.is_nullable || ' <> ' || e.nullable
                ELSE 'identity ' || c.is_identity END || ')', ', ')
    INTO problem
  FROM (VALUES
    ('cliente_enderecos','id',         'bigint',                     'NO'),
    ('cliente_enderecos','cliente_id', 'bigint',                     'NO'),
    ('cliente_enderecos','conta_id',   'uuid',                       'NO'),
    ('cliente_enderecos','tipo',       'text',                       'NO'),
    ('cliente_enderecos','logradouro', 'text',                       'NO'),
    ('cliente_enderecos','numero',     'text',                       'NO'),
    ('cliente_enderecos','complemento','text',                       'YES'),
    ('cliente_enderecos','bairro',     'text',                       'NO'),
    ('cliente_enderecos','cidade',     'text',                       'NO'),
    ('cliente_enderecos','estado',     'text',                       'NO'),
    ('cliente_enderecos','cep',        'text',                       'NO'),
    ('cliente_enderecos','created_at', 'timestamp with time zone',   'YES'),
    ('cliente_enderecos','updated_at', 'timestamp with time zone',   'YES'),
    ('cliente_datas',    'id',         'bigint',                     'NO'),
    ('cliente_datas',    'cliente_id', 'bigint',                     'NO'),
    ('cliente_datas',    'conta_id',   'uuid',                       'NO'),
    ('cliente_datas',    'titulo',     'text',                       'NO'),
    ('cliente_datas',    'data',       'date',                       'NO'),
    ('cliente_datas',    'created_at', 'timestamp with time zone',   'YES')
  ) AS e(tbl, col, typ, nullable)
  LEFT JOIN information_schema.columns c
    ON c.table_schema='public' AND c.table_name=e.tbl AND c.column_name=e.col
  WHERE c.column_name IS NULL
     OR c.data_type   IS DISTINCT FROM e.typ
     OR c.is_nullable IS DISTINCT FROM e.nullable
     OR (e.col = 'id' AND c.is_identity = 'YES');

  IF problem IS NOT NULL THEN
    RAISE EXCEPTION 'Adopted shape does not match production — %', problem;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint pc
    JOIN pg_class pcl ON pcl.oid = pc.conrelid
    JOIN pg_namespace pn ON pn.oid = pcl.relnamespace
    WHERE pn.nspname='public' AND pcl.relname='cliente_enderecos'
      AND pc.conname='cliente_enderecos_tipo_check' AND pc.contype='c'
  ) THEN
    RAISE EXCEPTION 'Missing CHECK constraint cliente_enderecos_tipo_check';
  END IF;
END $$;
