-- =============================================================
-- Links úteis do cliente (Drive, Notion, Figma...)
-- Spec: docs/superpowers/specs/2026-09-19-cliente-links-uteis-design.md
--
-- Mesmo modelo de cliente_enderecos: RLS pelo workspace ATIVO e, em
-- INSERT/UPDATE, cliente_id precisa pertencer ao mesmo conta_id da linha
-- (ver 20260728000004). O EXISTS qualifica cliente_links.conta_id de
-- proposito: um conta_id sem qualificacao resolveria para o proprio
-- `clientes c` e viraria tautologia.
-- =============================================================

CREATE TABLE IF NOT EXISTS public.cliente_links (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id  bigint NOT NULL REFERENCES public.clientes(id)   ON DELETE CASCADE,
  conta_id    uuid   NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
  titulo      text   NOT NULL,
  url         text   NOT NULL,
  descricao   text,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT cliente_links_titulo_check
    CHECK (char_length(btrim(titulo)) BETWEEN 1 AND 120),
  CONSTRAINT cliente_links_url_check
    CHECK (char_length(url) <= 2048 AND url ~* '^https?://[^[:space:]]+$'),
  CONSTRAINT cliente_links_descricao_check
    CHECK (descricao IS NULL OR char_length(descricao) <= 300)
);

CREATE INDEX IF NOT EXISTS idx_cliente_links_cliente_id
  ON public.cliente_links USING btree (cliente_id);
CREATE INDEX IF NOT EXISTS idx_cliente_links_conta_id
  ON public.cliente_links USING btree (conta_id);

ALTER TABLE public.cliente_links ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.cliente_links FROM anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.cliente_links TO authenticated;
GRANT ALL ON TABLE public.cliente_links TO service_role;

DO $$
DECLARE
  predicate constant text :=
    'conta_id IN (SELECT workspace_id FROM public.workspace_members '
    '             WHERE user_id = auth.uid()) '
    'AND conta_id IN (SELECT public.get_my_conta_id())';
  check_predicate constant text := predicate ||
    ' AND EXISTS (SELECT 1 FROM public.clientes c '
    '             WHERE c.id = cliente_links.cliente_id '
    '               AND c.conta_id = cliente_links.conta_id)';
BEGIN
  EXECUTE format('CREATE POLICY workspace_select_links ON public.cliente_links '
                 'FOR SELECT TO authenticated USING (%s)', predicate);
  EXECUTE format('CREATE POLICY workspace_insert_links ON public.cliente_links '
                 'FOR INSERT TO authenticated WITH CHECK (%s)', check_predicate);
  EXECUTE format('CREATE POLICY workspace_update_links ON public.cliente_links '
                 'FOR UPDATE TO authenticated USING (%s) WITH CHECK (%s)',
                 predicate, check_predicate);
  EXECUTE format('CREATE POLICY workspace_delete_links ON public.cliente_links '
                 'FOR DELETE TO authenticated USING (%s)', predicate);
END $$;

-- Pos-condicao: as quatro politicas existem e as de escrita carregam o
-- conjunto anti-corrupcao (perde-lo e a regressao que isto previne).
DO $$
DECLARE
  n int;
BEGIN
  SELECT count(*) INTO n FROM pg_policies
   WHERE schemaname = 'public' AND tablename = 'cliente_links';
  IF n <> 4 THEN
    RAISE EXCEPTION 'cliente_links: esperava 4 politicas, achei %', n;
  END IF;

  SELECT count(*) INTO n FROM pg_policies
   WHERE schemaname = 'public' AND tablename = 'cliente_links'
     AND cmd IN ('INSERT', 'UPDATE')
     AND coalesce(with_check, '') LIKE '%clientes%';
  IF n <> 2 THEN
    RAISE EXCEPTION 'cliente_links: WITH CHECK de INSERT/UPDATE sem a checagem de clientes';
  END IF;
END $$;
