-- =============================================================
-- Schema drift reconciliation (1/2) — ADOPT
-- See docs/superpowers/specs/2026-07-27-schema-drift-audit.md
--
-- cliente_enderecos and cliente_datas back the live Endereços and Datas
-- sections of the client detail page (apps/crm/src/store/clients.ts), but were
-- hand-created in production and never captured in a migration. They are absent
-- from staging, where those two features are consequently broken.
--
-- clientes.data_aniversario is in the same situation: read and written by the
-- app (ClienteDetalhePage, CalendarioPage) with no migration behind it.
--
-- This migration reproduces production's exact current shape. It is a no-op in
-- production and creates the objects everywhere else. Nothing here changes
-- production behaviour.
-- =============================================================

-- -------------------------------------------------------------
-- cliente_enderecos
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.cliente_enderecos (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id   bigint NOT NULL REFERENCES public.clientes(id)   ON DELETE CASCADE,
  conta_id     uuid   NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
  tipo         text NOT NULL DEFAULT 'comercial',
  logradouro   text NOT NULL DEFAULT '',
  numero       text NOT NULL DEFAULT '',
  complemento  text          DEFAULT '',
  bairro       text NOT NULL DEFAULT '',
  cidade       text NOT NULL DEFAULT '',
  estado       text NOT NULL DEFAULT '',
  cep          text NOT NULL DEFAULT '',
  created_at   timestamptz DEFAULT now(),
  updated_at   timestamptz DEFAULT now(),
  CONSTRAINT cliente_enderecos_tipo_check
    CHECK (tipo = ANY (ARRAY['residencial'::text, 'comercial'::text]))
);

CREATE INDEX IF NOT EXISTS idx_cliente_enderecos_cliente_id
  ON public.cliente_enderecos USING btree (cliente_id);
CREATE INDEX IF NOT EXISTS idx_cliente_enderecos_conta_id
  ON public.cliente_enderecos USING btree (conta_id);

ALTER TABLE public.cliente_enderecos ENABLE ROW LEVEL SECURITY;

-- -------------------------------------------------------------
-- cliente_datas
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.cliente_datas (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id  bigint NOT NULL REFERENCES public.clientes(id)   ON DELETE CASCADE,
  conta_id    uuid   NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
  titulo      text NOT NULL DEFAULT '',
  data        date NOT NULL,
  created_at  timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_cliente_datas_cliente_id
  ON public.cliente_datas USING btree (cliente_id);
CREATE INDEX IF NOT EXISTS idx_cliente_datas_conta_id
  ON public.cliente_datas USING btree (conta_id);

ALTER TABLE public.cliente_datas ENABLE ROW LEVEL SECURITY;

-- -------------------------------------------------------------
-- RLS policies — reproduced verbatim from production.
--
-- NOTE: these scope by *membership* (every workspace the caller belongs to)
-- rather than by the active workspace, so they differ from the
-- get_my_conta_id() pattern used elsewhere in this schema. That difference is
-- preserved deliberately: this migration adopts production as-is. Whether to
-- align them is a separate, deliberate decision.
-- -------------------------------------------------------------
DO $$
DECLARE
  t text;
  suffix text;
BEGIN
  FOREACH t IN ARRAY ARRAY['cliente_datas', 'cliente_enderecos'] LOOP
    suffix := replace(t, 'cliente_', '');

    EXECUTE format(
      'DROP POLICY IF EXISTS %I ON public.%I', 'workspace_read_' || suffix, t);
    EXECUTE format($f$
      CREATE POLICY %I ON public.%I FOR SELECT USING (
        conta_id IN (SELECT workspace_id FROM public.workspace_members
                     WHERE user_id = auth.uid()))$f$,
      'workspace_read_' || suffix, t);

    EXECUTE format(
      'DROP POLICY IF EXISTS %I ON public.%I', 'workspace_insert_' || suffix, t);
    EXECUTE format($f$
      CREATE POLICY %I ON public.%I FOR INSERT WITH CHECK (
        conta_id IN (SELECT workspace_id FROM public.workspace_members
                     WHERE user_id = auth.uid()))$f$,
      'workspace_insert_' || suffix, t);

    EXECUTE format(
      'DROP POLICY IF EXISTS %I ON public.%I', 'workspace_update_' || suffix, t);
    EXECUTE format($f$
      CREATE POLICY %I ON public.%I FOR UPDATE USING (
        conta_id IN (SELECT workspace_id FROM public.workspace_members
                     WHERE user_id = auth.uid()))$f$,
      'workspace_update_' || suffix, t);

    EXECUTE format(
      'DROP POLICY IF EXISTS %I ON public.%I', 'workspace_delete_' || suffix, t);
    EXECUTE format($f$
      CREATE POLICY %I ON public.%I FOR DELETE USING (
        conta_id IN (SELECT workspace_id FROM public.workspace_members
                     WHERE user_id = auth.uid()))$f$,
      'workspace_delete_' || suffix, t);
  END LOOP;
END $$;

-- -------------------------------------------------------------
-- clientes.data_aniversario — 'MM-DD' text, written by ClienteDetalhePage.
-- -------------------------------------------------------------
ALTER TABLE public.clientes
  ADD COLUMN IF NOT EXISTS data_aniversario text;

-- -------------------------------------------------------------
-- Post-condition: assert the adopted shape actually exists.
--
-- This is the whole point of the migration. `CREATE TABLE IF NOT EXISTS`
-- silently no-ops against a pre-existing table with a *different* shape — which
-- is precisely how production drifted from hub_brand.created_at and three other
-- columns without anyone noticing. Asserting afterwards converts that silent
-- skip into a loud failure.
-- -------------------------------------------------------------
DO $$
DECLARE
  missing text;
BEGIN
  SELECT string_agg(f.tbl || '.' || f.col, ', ')
    INTO missing
  FROM (VALUES
    ('cliente_enderecos','tipo'),       ('cliente_enderecos','logradouro'),
    ('cliente_enderecos','numero'),     ('cliente_enderecos','complemento'),
    ('cliente_enderecos','bairro'),     ('cliente_enderecos','cidade'),
    ('cliente_enderecos','estado'),     ('cliente_enderecos','cep'),
    ('cliente_enderecos','created_at'), ('cliente_enderecos','updated_at'),
    ('cliente_datas','titulo'),         ('cliente_datas','data'),
    ('cliente_datas','created_at'),     ('clientes','data_aniversario')
  ) AS f(tbl, col)
  WHERE NOT EXISTS (
    SELECT 1 FROM information_schema.columns c
    WHERE c.table_schema = 'public'
      AND c.table_name  = f.tbl
      AND c.column_name = f.col
  );

  IF missing IS NOT NULL THEN
    RAISE EXCEPTION 'Adoption incomplete — missing: %', missing;
  END IF;
END $$;
